// Package main is cmdb-test-app, generated by the CMDB platform scaffold.
//
// 这份骨架里已经处理好三件「写错不会报错、只会在发布时以毛刺出现」的事（impl/01 §5.5）：
//   1. SIGTERM → server.Shutdown，等在途请求结束（不等的话每次发布都丢一批请求）
//   2. /health 与 /readyz 分开：前者答「进程活着」，后者答「可以接流量」
//   3. /metrics 暴露 Prometheus 指标，平台按 app_key/team/env 注入 label
//
// 不要在这里写副本数、内存上限或探针参数——它们属于 SRE 的 Deployment Profile。写进代码之后
// 改 Profile 就不再生效，而没有任何地方会提示这件事。
package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// version is stamped at build time: -ldflags "-X main.version=<short_sha>"。
// 平台的构建计划已经带上这个参数，所以线上进程能自己说清它是哪个 commit。
var version = "dev"

// shutdownTimeout 必须小于集群给的 terminationGracePeriod（Profile 里是 45s）。
// 等得比它长的结果是每次发布都被 SIGKILL，在途请求全部失败。
const shutdownTimeout = 25 * time.Second

func main() {
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, nil)))

	// ready 在收到 SIGTERM 后立刻翻假：K8s 把「摘 endpoints」与「发 SIGTERM」并发做，
	// 而 ingress 的规则更新有延迟。先让 /readyz 失败，流量才会在关闭前被摘干净。
	var ready atomic.Bool
	ready.Store(true)

	mux := http.NewServeMux()

	mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("ok"))
	})

	mux.HandleFunc("/readyz", func(w http.ResponseWriter, _ *http.Request) {
		if !ready.Load() {
			w.WriteHeader(http.StatusServiceUnavailable)

			return
		}

		w.WriteHeader(http.StatusOK)
	})

	mux.Handle("/metrics", promhttp.Handler())

	mux.HandleFunc("/", func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte("cmdb-test-app " + version + "\n"))
	})

	srv := &http.Server{
		Addr:              ":8080",
		Handler:           mux,
		ReadHeaderTimeout: 10 * time.Second,
	}

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	go func() {
		slog.Info("listening", "addr", srv.Addr, "version", version)

		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			slog.Error("listen failed", "error", err)
			os.Exit(1)
		}
	}()

	<-ctx.Done()
	ready.Store(false)

	slog.Info("shutting down", "timeout", shutdownTimeout)

	// 这里必须用一个新的 context：ctx 已经被信号取消，继承它会让 Shutdown 立刻返回，
	// 在途请求全部被硬断——优雅停机形同虚设。
	shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()

	if err := srv.Shutdown(shutdownCtx); err != nil {
		slog.Error("shutdown failed", "error", err)
		os.Exit(1)
	}

	slog.Info("stopped")
}
